export const ALL_TASKS_REQUEST = "ALL_TASKS_REQUEST";
export const ALL_TASKS_SUCESS = "ALL_TASKS_SUCESS";
export const ALL_TASKS_FAIL = "ALL_TASKS_FAIL";

export const SINGLE_TASK_REQUEST = "SINGLE_TASK_REQUEST";
export const SINGLE_TASK_SUCESS = "SINGLE_TASK_SUCESS";
export const SINGLE_TASK_FAIL = "SINGLE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCESS = "DELETE_TASK_SUCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";

export const NEW_TASK_REQUEST = "NEW_TASK_REQUEST";
export const NEW_TASK_SUCESS = "NEW_TASK_SUCESS";
export const NEW_TASK_FAIL = "NEW_TASK_FAIL";
export const NEW_TASK_RESET = "NEW_TASK_RESET";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCESS = "UPDATE_TASK_SUCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET";

export const NEW_SUB_TASK_REQUEST = "NEW_SUB_TASK_REQUEST";
export const NEW_SUB_TASK_SUCESS = "NEW_SUB_TASK_SUCESS";
export const NEW_SUB_TASK_FAIL = "NEW_SUB_TASK_FAIL";
export const NEW_SUB_TASK_RESET = "NEW_SUB_TASK_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";