export const ALL_TASKS_REQUEST = "ALL_TASKS_REQUEST";
export const ALL_TASKS_SUCESS = "ALL_TASKS_SUCESS";
export const ALL_TASKS_FAIL = "ALL_TASKS_FAIL";

export const SINGLE_TASK_REQUEST = "SINGLE_TASK_REQUEST";
export const SINGLE_TASK_SUCESS = "SINGLE_TASK_SUCESS";
export const SINGLE_TASK_FAIL = "SINGLE_TASK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";